// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DataActions: typeof import('./src/components/DataActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBeakDataTable: typeof import('./src/components/V-BeakDataTable.vue')['default']
    VBeakDataTable_old: typeof import('./src/components/V-BeakDataTable_old.vue')['default']
    VButton: typeof import('./src/components/V-Button.vue')['default']
    VControl: typeof import('./src/components/V-Control.vue')['default']
    VField: typeof import('./src/components/V-Field.vue')['default']
    VFlexPagination: typeof import('./src/components/V-FlexPagination.vue')['default']
    VTableRow: typeof import('./src/components/V-TableRow.vue')['default']
  }
}
